mode: auto

avatar:
  url: /images/avatar.jpg
  status:
    enable: true
    emoji: ğŸŒ‘
    message: Looking for dawn.

banner:
  enable: true
  title: çˆ±æŠ˜è…¾çš„å°èƒ¡
  src: /js/ui/banner.js
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

wordcloud:
  enable: true

girls:
  enable: true
