mode: auto

avatar:
  url: /images/avatar.jpg
  status:
    enable: true
    emoji: ğŸŒ‘
    message: Looking for dawn.

banner:
  enable: true
  title: çˆ±æŠ˜è…¾çš„å°èƒ¡
  src: /js/ui/banner.js
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

wordcloud:
  enable: true

albums:
  enable: true

girls:
  enable: true

pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: icon-genderless-line
    color: dodgerblue
  - name: å–œæ¬¢çš„å¥³å­©å­
    url: /girls/
    icon: icon-women-line
    color: hotpink

